name: AutoBroadcaster
description: Broadcast messages to your server with ease!
main: AutoBroadcaster\Main
version: 1.2
api: [3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6]
author: PotatoeTrainYT
website: https://github.com/PotatoeTrainYT/AutoBroadcaster
