name: AutoBroadcaster
description: Broadcast messages to your server with ease!
main: AutoBroadcaster\Main
version: 1.2
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: PotatoeTrainYT
website: https://github.com/PotatoeTrainYT/AutoBroadcaster
