---
# AutoBroadcaster Settings

# Seconds between each broadcasted message
seconds: 300

# Put the messages you want to be broadcasted here:
messages:
 - "&eAutoBroadcaster"
 - "&aMade By &bPotatoeTrainYT"

# Variables for messages above:
# & ~ Use for color coding messages
# {MAX_PLAYERS} ~ Gets servers max players limit
# {ONLINE} ~ Gets servers online players count
...
